import 'package:antinote/src/helpers/json.dart';
import 'package:antinote/src/models/period.dart';

final class const ReportDisplayInformation({
  required final bool withAppreciationPerSubService,
  required final bool withAbsencesDuration,
  required final bool withWeekLessonDuration,
  required final bool withCoefficient,
  required final bool withExamCount,
  required final bool withStudentRanking, // classement
  required final bool withStudentPointCount,
  required final bool withStudentPointBetween,
  required final bool withEvolution,
  required final int averagePeriodCount,
  required final bool withGeneralAverage,
  required final bool withGeneralRanking,
  required final bool withStudentAverage,
  required final bool withStudentMasteryLevel,
  required final bool withProposedAverage,
  required final bool withDeliberatedAverage,
  required final bool withClassAverage,
  required final bool withClassMedian,
  required final bool withWorstBestAverages,
  required final bool withPeriodAverage,
  required final bool withYearlyAverage,
  required final int appreciationCount,
  required final bool withECTS,
  required final bool alignAverageToTheRight,
  required final bool withProgramElements,
  required final bool withExamComments,
  required final bool withExamDates,
  required final bool withExamCoefficients,
  required final bool withCompleteExams,
  required final bool withSubServices,

  required final List<dynamic> periodsData,

  required final List<Period> periodLabels,
  required final List<Period> abbreviatedPeriods,

  required final List<dynamic> appreciationLabelsData,
}) {
  factory decode(Map<String, dynamic> nav) => .new(
    withAppreciationPerSubService: nav.get('AvecAppreciationParSousService'),
    withAbsencesDuration: nav.get('AvecDureeDesAbsenses'),
    withWeekLessonDuration: nav.get('AvecVolumeHoraire'),
    withCoefficient: nav.get('AvecCoefficient'),
    withExamCount: nav.get('AvecNombreDevoirs'),
    withStudentRanking: nav.get('AvecClassementEleve'),
    withStudentPointCount: nav.get('AvecNombrePointsEleve'),
    withStudentPointBetween: nav.get('AvecNombrePointsEntre'),
    withEvolution: nav.get('AvecEvolution'),
    averagePeriodCount: nav.get('NombreMoyennesPeriodes'),
    withGeneralAverage: nav.get('AvecMoyenneGenerale'),
    withGeneralRanking: nav.get('AvecClassementGeneral'),
    withStudentAverage: nav.get('AvecMoyenneEleve'),
    withStudentMasteryLevel: nav.get('AvecNivMaitriseEleve'),
    withProposedAverage: nav.get('AvecMoyenneProposee'),
    withDeliberatedAverage: nav.get('AvecMoyenneDeliberee'),
    withClassAverage: nav.get('AvecMoyenneClasse'),
    withClassMedian: nav.get('AvecMoyenneMediane'),
    withWorstBestAverages: nav.get('AvecMoyenneInfSup'),
    withPeriodAverage: nav.get('AvecMoyennePeriode'),
    withYearlyAverage: nav.get('AvecMoyenneAnnuelle'),
    appreciationCount: nav.get('NombreAppreciations'),
    withECTS: nav.get('avecECTS'),
    alignAverageToTheRight: nav.get('alignementMoyADroite'),
    withProgramElements: nav.get('avecElementProgramme'),
    withExamComments: nav.get('avecDevoirsCommentaire'),
    withExamDates: nav.get('avecDevoirsDate'),
    withExamCoefficients: nav.get('avecDevoirsCoefficient'),
    withCompleteExams: nav.get('avecDevoirComplet'),
    withSubServices: nav.get('AvecSousService'),
    periodsData: nav.getL('listePeriodes'),
    periodLabels: nav.getLM('listeLibellesPeriodes').mapL((e) => .decode(e)),
    abbreviatedPeriods: nav
        .getLM('listeAbbreviationsPeriodes')
        .mapL((e) => .decode(e)),
    appreciationLabelsData: nav.getL('ListeIntitulesAppreciations'),
  );
}
