syntax = "proto3";
package antinote;

import "protos/antinote/workspace.proto";

message SerializedCrypto {
  // 16 bytes for the AES Initialization Vector used in the relevant session.
  bytes iv = 1;
  // The unknown-length key given by the remote to communicate with the server.
  bytes key = 2;
  // The RSA modulo for the session, if one is given by the remote (else we use the default).
  optional string rsa_modulus = 3;
  // The RSA exponent for the session, if one is given by the remote (else we use the default).
  optional string rsa_exponent = 4;
}

message ServerSignature {
  enum ConnectionStatus {
    AVAILABLE = 0;
    IN_CLASS = 1;
    DO_NOT_DISTURB = 2;
    DISCONNECTED = 3;
  }
  /*
    final bool exclusiveMode;

  final Map<int, int> notificationCountPerTab;

  // final bool updateMessages; Just send the update through a listener or an equivalent (actualisationMessage or notificationsChatVS != null)
  // final bool updateKiosk; Just send the update through a listener or an equivalent (notificationsKiosque)

  // final List<Alert> alerts; We don't do alerts yet (notificationsChatVS)

  final int visibleNotificationsCount; // compteurCentraleNotif
  final int connectionStatus; // statutConnexion

  // unused notification types: dureeMAJServeur, MAJAnnulation, tokenOAuth2, and actualisation_postForum
  // unused data notification types (at listeDonnees) :

   for 2, THND_ListeGroupe for 3, THND_ListeProfesseur for 4, and THND_ListeDocJointEtablissement for 0
  final Map<String, dynamic>? extraData;*/

  // Whether the app is in the "exclusive" mode. If true, no edit requests can be sent (it is recommended the UI should update accordingly).
  bool exclusiveMode = 1;
  // Tells how many notifications are active for relevant tabs.
  map<uint32, uint32> tab_notification_counts = 2;
  // Used to know how many notifications are currently active.
  uint32 visible_notifications_count = 3;
  // The status for the current account (used for communication).
  ConnectionStatus connection_status = 4;

  // Unused data goes here, when information is not parsed successfully, it is stored as its raw for here.
  // Currently, here are the fields that are not parsed:
  // ```json
  // {
  //   "droits": {
  //     "...": true // Rights management is not implemented yet.
  //   }
  //   "notifications": {
  //     "dureeMAJServeur": 1000, // In milliseconds.
  //     "MAJAnnulation": true, // Actual type is unknown, this will probably be available as an event.
  //     "tokenOAuth2": {
  //       "ok": true, // Whether login was successful.
  //       "message": "Error" // Only present when [ok] field is false (or maybe absent).
  //     },
  //     "actualisation_postForum": true, // Actual type is unknown, this will probably be available as an event.
  //     "listeDonnees": {
  //       "2": [], // Visibly unused (class list per level).
  //       "3": [], // Visibly unused (group list).
  //       "4": [], // Visibly unused (teacher list).
  //       "0": [] // Used (attachment list for an establishment). No instance was found where this is actually used. Although, this seems to be an element list.
  //     }
  //   }
  // }
  // ```
}

message ClientSignature {
  message Member {
    string id = 1;
    uint32 type = 2;
  }

  // The currently selected tab.
  sint32 tab = 1;
  // The currently selected member.
  optional Member member = 2;
}

message SerializedNetworkStack {
  SerializedCrypto crypto = 1;
  string instance_version = 2;
  string base_url = 3;
  repeated string cookies = 4;
  SerializedWorkspace temp_workspace = 5;
  bool demo = 6;
  bool rsa_from_constants = 7;
  bool skip_encryption = 8;
  bool skip_compression = 9;
  bool http = 10;
  bool poll = 11;
  string username = 12;
  uint32 session_id = 13;
  optional string token_id = 14;
  optional string token_key = 15;
  optional ClientSignature client_signature = 16;
  optional ServerSignature server_signature = 17;
  map<string, sint32> orders = 18;
}

enum CacheType {
  // SPECIAL CACHE TYPE
  //
  // Will simply give out the latest value for each item type put in cache when
  // asked (this is just a marker where we expect any object that wants to
  // replace versions of it by putting the same constant visual ID).
  UNIQUE = 0;
  PERIOD = 1;
  DISCUSSION_MESSAGE = 2;
  FILE_ATTACHMENT = 3;
  LINK_ATTACHMENT = 4;
  SUBMITTED_FILE_ATTACHMENT = 5;
  DISCUSSION_NODE = 6;
  SERVICE = 7;
  EXAM = 8;
  THEME = 9;
  MEAL = 10;
  FOOD = 11;
  FOOD_LABEL = 12;
  FOOD_ALLERGEN = 13;
  NEWS = 14;
  PERSON = 15;
  NEWS_CATEGORY = 16;
  NEWS_QUESTION = 17;
  NEWS_QUESTION_PICK = 18;
  NEWS_QUESTION_ANSWER = 19;
  NOTEBOOK_ENTRY = 20;
  NOTEBOOK_ENTRY_GROUP = 21;
  NOTEBOOK_CONTENT = 22;
  NOTEBOOK_CONTENT_CATEGORY = 23;
  HOMEWORK = 24;
  HANDED_ASSIGNMENT = 25;
  NOTEBOOK_RESOURCE_ENTRY = 26;
  CLAZZ = 27;
  SUBJECT = 28;
  NOTEBOOK_ENTRY_PREVIEW = 29;
  NOTEBOOK_RESOURCE = 30;
  PEDAGOGICAL_FORUM = 31;
  MCQ_EXECUTION = 32;
  MCQ = 33;
  EXAM_PREVIEW = 34;
  ROOM = 35;
  SCHOOL_LIFE_EVENT = 36;
  SCHOOL_LIFE_EVENT_REASON = 37;
  SCHOOL_LIFE_EVENT_SECTION = 38;
  USER_RESOURCE = 39;
  HOLIDAY = 40;
  CLASSROOM = 41;
  CLASS_GROUP = 42;
  STUDENT_CLASS = 43;
  CLASS_CONTENT = 44;
}

message CacheSection {
  CacheType type = 1;
  map<string, string> values = 2;
}

message SerializedSession {
  SerializedNetworkStack stack = 1;
  repeated CacheSection cache = 2;
}

message SessionOptions {
  // When this field is true, Navigation requests won't be sent from ensurePage.
  bool saveNavigationRequests = 1;
  // Will log every single request sent and received to/from remote.
  bool debugMode = 2;
}